/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GCard: typeof import('./src/components/g-card/index.vue')['default']
    GFooter: typeof import('./src/components/g-footer/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    IconPicker: typeof import('./src/components/icon/picker.vue')['default']
    IconSvgIcon: typeof import('./src/components/icon/svg-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test/index.vue')['default']
  }
}
