export { default as Title } from './Title.vue'
export { default as GHeader } from './GHeader.vue'
export { default as Banner } from './Banner.vue'
export { default as GSearch } from './GSearch.vue'
export { default as NewGame } from './NewGame.vue'
export { default as Ranking } from './Ranking.vue'
export { default as Recommend } from './Recommend.vue'
